clone_depth: 10

# Needs this for most recent MSYS
image: Visual Studio 2019

environment:
  global:
    MSYS2_DIR: C:\msys64
    MSYS2_ASH: C:\msys64\usr\bin\ash.exe
    MSYS2_BASH: C:\msys64\usr\bin\bash.exe

cache:
  - '%MSYS2_DIR%\var\cache\pacman'

install:
  - '%MSYS2_BASH% --login -c "pacman -Syu --noconfirm"'
  - '%MSYS2_BASH% --login -c "pacman -Syu --noconfirm"'
  - '%MSYS2_BASH% --login -c "pacman -S --noconfirm --needed base-devel msys2-devel gcc"'
  - '%MSYS2_BASH% --login -c "pacman -S --noconfirm --needed python3 python3-pip"'
  - '%MSYS2_BASH% --login -c "pacman -S --noconfirm --needed libffi libffi-devel"'
  - '%MSYS2_BASH% --login -c "pacman -S --noconfirm --needed openssl openssl-devel libcrypt libcrypt-devel"'
  - '%MSYS2_BASH% --login -c "pacman -S --noconfirm --needed libyaml-devel"'
  - '%MSYS2_BASH% --login -c "pacman -S --noconfirm --needed git openssh rsync tar"'
  - '%MSYS2_BASH% --login -c "pacman -S --noconfirm --needed p7zip"'

  - ps: Get-Process | Where-Object { $_.Path -like "${env:MSYS2_DIR}*" } | Stop-Process
  - '%MSYS2_ASH% -c "/usr/bin/rebaseall -v"'

  - '%MSYS2_BASH% --login -c "python3 -mpip install --upgrade pip"'
  - '%MSYS2_BASH% --login -c "python3 -mpip install ''cryptography==3.3.1''"'
  - '%MSYS2_BASH% --login -c "python3 -mpip install ''pywinrm>=0.3.0''"'
  - '%MSYS2_BASH% --login -c "python3 -mpip install ansible"'

  - ps: Get-Process | Where-Object { $_.Path -like "${env:MSYS2_DIR}*" } | Stop-Process
  - '%MSYS2_ASH% -c "/usr/bin/rebaseall -v"'

build_script:
  - '%MSYS2_BASH% --login -c "cd $APPVEYOR_BUILD_FOLDER && ./release.sh"'

artifacts:
  - path: winsible.7z
    name: winsible.7z
    type: file
