clone_depth: 10

# Needs this for most recent MSYS
image: Visual Studio 2019

environment:
  global:
    MSYS2_DIR: C:\msys64
    MSYS2_ASH: C:\msys64\usr\bin\ash.exe
    MSYS2_BASH: C:\msys64\usr\bin\bash.exe

cache:
  - '%MSYS2_DIR%\var\cache\pacman'

install:
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

  - '%MSYS2_BASH% --login -c "pacman -Syu --noconfirm"'
  - '%MSYS2_BASH% --login -c "pacman -Syu --noconfirm"'
  - '%MSYS2_BASH% --login -c "pacman -S --noconfirm --needed base-devel msys2-devel gcc"'
  - '%MSYS2_BASH% --login -c "pacman -S --noconfirm --needed libffi libffi-devel"'
  - '%MSYS2_BASH% --login -c "pacman -S --noconfirm --needed openssl openssl-devel libxcrypt libxcrypt-devel"'
  - '%MSYS2_BASH% --login -c "pacman -S --noconfirm --needed libyaml-devel"'
  - '%MSYS2_BASH% --login -c "pacman -S --noconfirm --needed git openssh rsync tar"'
  - '%MSYS2_BASH% --login -c "pacman -S --noconfirm --needed p7zip"'
  - '%MSYS2_BASH% --login -c "pacman -S --noconfirm --needed mingw-w64-x86_64-python mingw-w64-x86_64-python-pip"'
  - '%MSYS2_BASH% --login -c "pacman -S --noconfirm --needed mingw-w64-x86_64-python-cryptography mingw-w64-x86_64-python-sspilib"'

  #- ps: Get-Process | Where-Object { $_.Path -like "${env:MSYS2_DIR}*" } | Stop-Process
  #- '%MSYS2_ASH% -c "/usr/bin/rebaseall -v"'

  - '%MSYS2_BASH% --login -c "/mingw64/bin/python3 -mpip install pywinrm"'
  - '%MSYS2_BASH% --login -c "/mingw64/bin/python3 -mpip install ansible"'

  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

  #- ps: Get-Process | Where-Object { $_.Path -like "${env:MSYS2_DIR}*" } | Stop-Process
  #- '%MSYS2_ASH% -c "/usr/bin/rebaseall -v"'

build_script:
  - '%MSYS2_BASH% --login -c "cd $APPVEYOR_BUILD_FOLDER && ./release.sh"'

artifacts:
  - path: winsible.7z
    name: winsible.7z
    type: file
